// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_pCW7MVqgXZGKsycKCQt5sfcIE_ZLwuA',
    appId: '1:618787130343:web:ee6dca8b37dd9031850b42',
    messagingSenderId: '618787130343',
    projectId: 'todogetx-d2132',
    authDomain: 'todogetx-d2132.firebaseapp.com',
    storageBucket: 'todogetx-d2132.firebasestorage.app',
    measurementId: 'G-PJTTGSYEE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz6YljVJtCM9JWqCApinnBPJ3Yj6PsXds',
    appId: '1:618787130343:android:82016efe9ac31417850b42',
    messagingSenderId: '618787130343',
    projectId: 'todogetx-d2132',
    storageBucket: 'todogetx-d2132.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVvAsq_H57STEfhOautneauRvJM-UJgbw',
    appId: '1:618787130343:ios:5c69c98a3e6950cd850b42',
    messagingSenderId: '618787130343',
    projectId: 'todogetx-d2132',
    storageBucket: 'todogetx-d2132.firebasestorage.app',
    iosBundleId: 'com.example.getxApp',
  );
}
